# Generated by Django 3.2.5 on 2021-09-02 14:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The title of the project.', max_length=80)),
                ('description', models.TextField(help_text='Project description.')),
                ('progress', models.IntegerField(default=0, help_text='The progress bar value', validators=[django.core.validators.MaxValueValidator(100)])),
                ('members', models.IntegerField(default=0, help_text='The number of people is working on thr project', validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The task title for the project.', max_length=30)),
                ('info', models.TextField(help_text='Additional info about the task.', null=True)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='The date the task was created.')),
                ('status', models.BooleanField(default=False, verbose_name='The task is finished or not.')),
                ('closed_date', models.DateField(verbose_name='The date the task was completed.')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectp.project')),
            ],
        ),
    ]
